#define intreg 1
#define adevar 2
#define caractere 3
#define daca 4
#define altfel 5
#define citeste 6
#define afiseaza 7
#define merge 8
#define lista 9
#define incepe 10
#define sfarsit 11
#define mergeee 12
#define baga 13
#define id 14
#define ct 15
#define plus 16
#define minus 17
#define inmultire 18
#define impartire 19
#define rest 20
#define mic 21
#define micE 22
#define egal 23
#define mareE 24
#define mare 25
#define atribuie 26
#define acoladaD 27
#define acoladaI 28
#define patratD 29
#define patratI 30
#define parantezaD 31
#define parantezaI 32
#define punctVirgula 33
#define virgula 34